'''
Step 4: stitches the 8 per-frame debug/visualization images already produced for one
scene pair into a single lossless 2x4 grid per frame, so one image shows how a frame
looks at every stage of the pipeline plus ground truth:

    [detected_masks] [fused_masks]            [scenegraph_viz]            [debug_masks]
    [filtered_masks] [fused_masks_with_nodes] [scenegraph_viz_with_edges] [gt_mask_viz]

detected_masks/filtered_masks/fused_masks/fused_masks_with_nodes/scenegraph_viz/
scenegraph_viz_with_edges come from slam/rerun_realtime_mapping.py (step 1), under
<output_root>/<pair>/concept_graphs/<before|after>/exps/r_mapping_pilot/. debug_masks
comes from step 2 (slam/convert_concept_graphs_to_scene_diff_benchmark_data.py), under
<output_root>/<pair>/benchmark_data/debug_masks/<before|after>/. gt_mask_viz comes from
the separate scene_diff/scripts/visualize_gt_masks.py (scripts/visualize-gt-masks.sh),
under a different root entirely, <ground_truth_root>/<pair>/gt_mask_viz/<before|after>/
-- it is not generated by run.sh and may be missing for a pair that hasn't had
visualize-gt-masks.sh run for it yet (that panel then renders as "missing").

All 8 sources are keyed by the same plain, unpadded integer frame index in their
filename stem, so they join cleanly across the 3 different roots above.

All 8 sources share the same aspect ratio (7 of them are literally the same
ConceptGraph-dataset frame at the same resolution; gt_mask_viz is that same video at
its original capture resolution, same ratio), so panels are joined edge-to-edge with no
padding/letterboxing. Every panel is resized to the largest resolution found among the
8 for that (pair, variant) -- i.e. only ever upscaled, never downscaled -- so no source
image's detail is thrown away; the panel that's already at that size is used byte-exact
(no resize call at all).

Usage:
    python -m conceptgraph.utils.combine_scene_vis_grid --pair_name <pair> \
        [--output_root <path>] [--ground_truth_root <path>]

Output: <output_root>/<pair>/vis/<before|after>/<n>.jpg
'''
import argparse
import re
from pathlib import Path

import cv2
import hydra
import numpy as np

from conceptgraph.utils.general_utils import EXP_SUFFIX

_FRAME_NUM_RE = re.compile(r"^(\d+)")

# 2 rows x 4 cols, matching the requested "1 3 5 7 / 2 4 6 8" layout.
_GRID_SLOTS = [[1, 3, 5, 7], [2, 4, 6, 8]]

_MISSING_COLOR = (40, 40, 40)


def _frame_num(stem: str):
    m = _FRAME_NUM_RE.match(stem)
    return int(m.group(1)) if m else None


def _collect_frames(source_dirs: dict) -> dict:
    '''source_dirs: {slot: (dir_path, suffix_strip)}. Returns {frame_num: {slot: path}},
    the union of frame numbers found across every present source directory -- a source
    missing entirely (e.g. gt_mask_viz for a pair visualize-gt-masks.sh hasn't been run
    for yet) just means that slot renders as "missing" for every frame rather than the
    scene producing no grids at all.'''
    frames = {}
    for slot, (d, suffix_strip) in source_dirs.items():
        if not d.is_dir():
            continue
        for p in d.iterdir():
            if not p.is_file():
                continue
            stem = p.stem
            if suffix_strip and stem.endswith(suffix_strip):
                stem = stem[: -len(suffix_strip)]
            n = _frame_num(stem)
            if n is None:
                continue
            frames.setdefault(n, {})[slot] = p
    return frames


def _probe_cell_size(source_dirs: dict, frames: dict) -> tuple:
    '''Reads one sample image per present source and returns (max_w, max_h) across
    them -- the size every panel is resized to (upscale-only, see _resize_to).'''
    max_w, max_h = 1, 1
    seen_dirs = set()
    for per_slot in frames.values():
        for slot, path in per_slot.items():
            d = source_dirs[slot][0]
            if d in seen_dirs:
                continue
            img = cv2.imread(str(path))
            if img is None:
                continue
            seen_dirs.add(d)
            h, w = img.shape[:2]
            max_w, max_h = max(max_w, w), max(max_h, h)
        if len(seen_dirs) == len(source_dirs):
            break
    return max_w, max_h


def _resize_to(img, size):
    '''Resizes img to (w, h) -- a no-op (returned as-is, no interpolation) when it's
    already that size, which by construction (size = _probe_cell_size's max over the 8
    sources) is true for whichever source is the largest. All 8 sources share one
    aspect ratio (see module docstring), so this never distorts proportions and every
    smaller source is only ever upscaled, never downscaled -- no detail is discarded.'''
    w, h = size
    ih, iw = img.shape[:2]
    if (iw, ih) == (w, h):
        return img
    return cv2.resize(img, (w, h), interpolation=cv2.INTER_LANCZOS4)


def _load_or_missing(path, size):
    w, h = size
    if path is not None:
        img = cv2.imread(str(path))
        if img is not None:
            return _resize_to(img, size)
    canvas = np.full((h, w, 3), _MISSING_COLOR, dtype=np.uint8)
    cv2.putText(canvas, "missing", (10, h // 2), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (120, 120, 120), 2)
    return canvas


def _make_grid_image(paths: dict, cell_size) -> np.ndarray:
    rows = []
    for row_slots in _GRID_SLOTS:
        cells = [_load_or_missing(paths.get(slot), cell_size) for slot in row_slots]
        rows.append(cv2.hconcat(cells))
    return cv2.vconcat(rows)


def combine_scene_vis_grid(pair_name: str, output_root, ground_truth_root) -> None:
    scene_root = Path(output_root) / pair_name
    ground_truth_root = Path(ground_truth_root)

    for variant in ("before", "after"):
        exp_out_path = scene_root / "concept_graphs" / variant / "exps" / EXP_SUFFIX
        source_dirs = {
            1: (exp_out_path / "detected_masks", ""),
            2: (exp_out_path / "filtered_masks", ""),
            3: (exp_out_path / "fused_masks", ""),
            4: (exp_out_path / "fused_masks_with_nodes", ""),
            5: (exp_out_path / "scenegraph_viz", "_viz"),
            6: (exp_out_path / "scenegraph_viz_with_edges", "_viz"),
            7: (scene_root / "benchmark_data" / "debug_masks" / variant, ""),
            8: (ground_truth_root / pair_name / "gt_mask_viz" / variant, ""),
        }

        frames = _collect_frames(source_dirs)
        if not frames:
            print(f"[{pair_name}/{variant}] no frames found across any of the 8 sources, skipping")
            continue

        cell_size = _probe_cell_size(source_dirs, frames)
        out_dir = scene_root / "vis" / variant
        out_dir.mkdir(parents=True, exist_ok=True)
        for n in sorted(frames):
            grid = _make_grid_image(frames[n], cell_size)
            cv2.imwrite(str(out_dir / f"{n}.jpg"), grid)

        print(f"[{pair_name}/{variant}] wrote {len(frames)} vis grids ({cell_size[0]}x{cell_size[1]} cells) -> {out_dir}")


def _load_output_root(output_root_override: str | None = None) -> Path:
    """Reads output_root from rerun_realtime_mapping.yaml -- the single source of
    truth for where pipeline outputs live -- via hydra.compose(), the same
    hydra_configs/ rerun_realtime_mapping.py loads with
    @hydra.main(config_path="../hydra_configs/", config_name="rerun_realtime_mapping").
    hydra.initialize() resolves config_path relative to this file's directory, so the
    override below points at conceptgraph/hydra_configs/ via conceptgraph/slam/ (the
    same directory rerun_realtime_mapping.py itself resolves "../hydra_configs" from).
    output_root_override mirrors passing output_root=... on rerun_realtime_mapping.py's
    CLI, so this stage agrees with the other 3 on where a given run's outputs live even
    when that run didn't use the yaml's default output_root."""
    overrides = [f"output_root={output_root_override}"] if output_root_override else []
    with hydra.initialize(version_base=None, config_path="../hydra_configs"):
        cfg = hydra.compose(config_name="rerun_realtime_mapping", overrides=overrides)
    return Path(cfg.output_root).resolve()


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pair_name", required=True)
    parser.add_argument("--output_root", default=None,
                         help="Overrides the yaml's output_root, like output_root=... on rerun_realtime_mapping.py's CLI")
    parser.add_argument("--ground_truth_root", default=None,
                         help="Root containing <pair>/gt_mask_viz/<before|after>/ (default: <repo>/ground-truth, "
                              "matching scripts/visualize-gt-masks.sh's own default)")
    args = parser.parse_args()

    output_root = args.output_root or _load_output_root()
    ground_truth_root = args.ground_truth_root or (Path(__file__).resolve().parents[3] / "ground-truth")

    combine_scene_vis_grid(
        pair_name=args.pair_name,
        output_root=output_root,
        ground_truth_root=ground_truth_root,
    )


if __name__ == "__main__":
    main()
